export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  CREATOR: "/creator",
  CREATOR_NEW: "/creator/new",
  CREATOR_ANALYTICS: "/creator/analytics",
  CREATOR_PAYOUTS: "/creator/payouts",
  SUBSCRIBE: "/subscribe",
  SUBSCRIBE_SUCCESS: "/subscribe/success",
  SUBSCRIBE_CANCEL: "/subscribe/cancel",
  SETTINGS: "/settings",
  SETTINGS_SUBSCRIPTION: "/settings/subscription",
  AUTH_LOGIN: "/auth/login",
  AUTH_REGISTER: "/auth/register",
  AUTH_VERIFY: "/auth/verify",
  AUTH_FORGOT: "/auth/forgot-password",
  MATCHES: "/matches",
  MATCH_DETAIL: (id: string) => `/matches/${id}`,
  BETTING: "/betting",
  BETTING_MODELS: "/betting/models",
  BETTING_TRACKER: "/betting/tracker",
  SCOUTING: "/scouting",
  SCOUTING_PLAYER: (id: string) => `/scouting/players/${id}`,
  SCOUTING_DISCOVER: "/scouting/discover",
  COMMUNITY: "/community",
  COMMUNITY_FORUM: (id: string) => `/community/${id}`,
  LIVE: "/live",
  LIVE_ROOM: (id: string) => `/live/${id}`,
  ENTERPRISE: "/enterprise",
} as const;
